image: Visual Studio 2019

before_build:
  - ps: |
      $ErrorActionPreference = "Stop"
      $directory_path = "$env:APPVEYOR_BUILD_FOLDER\Semester2\"
      $solution_names = (Get-ChildItem -Path $directory_path -Recurse -Include *.sln).FullName

build_script:
  - ps: |
      foreach ($name in $solution_names) 
      {
        dotnet build $name
        if ($LastExitCode -ne 0) 
        { 
          $host.SetShouldExit($LastExitCode)  
        }
      }

test_script:
  - ps: |
      foreach ($name in $solution_names) 
      {
        dotnet test $name
        if ($LastExitCode -ne 0) 
        { 
          $host.SetShouldExit($LastExitCode)  
        }
      }