image: Visual Studio 2019

before_build:
  - nuget restore myCoolHomework/Homework.sln

environment:
  matrix:
  - solution_name: Semester2\Homeworks\HW2\Task3\Task3.sln

build_script:
  - dotnet build %solution_name%

test_script:
  - dotnet test %solution_name%
